cog:
  environment:
    - SLACK_API_TOKEN=${SLACK_API_TOKEN}
    - COG_BOOTSTRAP_USERNAME=admin
    - COG_BOOTSTRAP_PASSWORD=changeme
    - COG_BOOTSTRAP_EMAIL_ADDRESS=cog@localhost
    - COG_BOOTSTRAP_FIRST_NAME=Cog
    - COG_BOOTSTRAP_LAST_NAME=Administrator
    - COG_API_URL_HOST=${COG_HOST}
    - COG_API_URL_PORT=80
    - COG_TRIGGER_URL_HOST=${COG_HOST}
    - COG_TRIGGER_URL_PORT=4001
    - COG_SERVICE_URL_HOST=${COG_HOST}
    - COG_SERVICE_URL_PORT=4002
    - RELAY_ID=00000000-0000-0000-0000-000000000000
    - RELAY_COG_TOKEN=supersecret

relay:
  environment:
    - RELAY_ID=00000000-0000-0000-0000-000000000000
    - RELAY_COG_TOKEN=supersecret
